### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [mcuntz/jams_fortran#2]
I suggest adding topics such as `numerical-methods`, `random-numbers`, `date`, `time`, `numerical-optimization` in the About section.

**Comment by mcuntz** [comment]
Hey @Beliavsky ,

I understand that the project is not so well documented. The routines themselves are well documented, though.

The README.md already has the sections:
    [Computational](https://github.com/mcuntz/jams_fortran#comp)
    [Date and Time](https://github.com/mcuntz/jams_fortran#date)
    [Input / Output](https://github.com/mcuntz/jams_fortran#io)
    [Math / Numerics](https://github.com/mcuntz/jams_fortran#math)
    [Screening, Sensitivity Analysis and Optimising / Fitting](https://github.com/mcuntz/jams_fortran#opti)
    [Miscellaneous](https://github.com/mcuntz/jams_fortran#misc)
some of which are topics that you proposed. So I was thinking that if I have not well understood your suggestion.

Kind regards,
Matthias

**Comment by Beliavsky** [comment]
The suggestion is to list topics in the About section, as done at https://github.com/jacobwilliams/PowellOpt , so that if someone
searches GitHub `language:fortran topic:numerical-methods` your repo will appear. How to add topics is described at https://docs.github.com/en/enterprise-server@3.0/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

**Comment by mcuntz** [comment]
@Beliavsky 
thanks for the suggestion. I was not aware of topics on github. I will do that soon.

Kind regards,
Matthias
